- name: Installation et configuration de SNMP sur AlmaLinux  # Nom de la tâche
  hosts: "{{ target }}"  # Les hôtes sur lesquels cette tâche sera exécutée
  become: yes  # Nécessite les privilèges d'administration pour exécuter les tâches

  tasks:  # Début des tâches à exécuter
    - name: Installation du paquet SNMP  # Nom de la tâche
      package:  # Utilisation du module package pour gérer les paquets
        name: net-snmp  # Nom du paquet à installer
        state: present  # Assure que le paquet est installé

    - name: Configuration du fichier de configuration SNMP  # Nom de la tâche
      template:  # Utilisation du module template pour gérer les fichiers de configuration
        src: snmpd.conf.j2  # Source du fichier de configuration SNMP
        dest: /etc/snmp/snmpd.conf  # Emplacement où le fichier sera placé
      register: result_configure_snmp  # Enregistre le résultat de la tâche

    - name: Redémarrer le service SNMP  # Nom de la tâche
      service:  # Utilisation du module service pour gérer les services
        name: snmpd  # Nom du service SNMP
        state: restarted  # Redémarre le service
      register: result_restart_snmp  # Enregistre le résultat de la tâche
      when: result_configure_snmp.changed  # Condition pour exécuter cette tâche seulement si la configuration a été modifiée

    - name: Afficher un message si aucune modification de la configuration n'a été effectuée  # Nom de la tâche
      debug:  # Utilisation du module debug pour afficher un message
        msg: "Le service SNMP est déjà installé et configuré sur cette machine."  # Message à afficher
      when: not (result_restart_snmp.changed)  # Condition pour exécuter cette tâche seulement si aucune modification n'a été effectuée
